[project]
name = "pynet"
version = "0.1.0"
description = "Framework CLI para inicializacion de proyectos de python en NetApplications"
dependencies = [
    "typer>0.9.0",
    "jinja2>3.1.0",
    "python-dotenv>1.0.0",
    "PyYAML>6.0"
]

[project.scripts]
pynet = "pynet.cli.app:app"
